version: "3.7"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: books
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: books_db
    volumes:
      -  db_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db_data:
